const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const toast=(msg)=>{const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)};
const scrollToEl=s=>$(s)?.scrollIntoView({behavior:"smooth",block:"start"});

$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("algoTheme",document.body.classList.contains("dark")?"dark":"light");$("#themeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾"};
if(localStorage.getItem("algoTheme")==="dark"){$("body").classList.add("dark");$("#themeBtn").textContent="☀"}
$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");
$$(".nav-link").forEach(a=>a.onclick=()=>$("#sidebar").classList.remove("open"));
$$("[data-scroll]").forEach(b=>b.onclick=()=>scrollToEl(b.dataset.scroll));

const sections=[...$$(".section")], nav=[...$$(".nav-link")];
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){nav.forEach(n=>n.classList.toggle("active",n.getAttribute("href")===`#${e.target.id}`))}}),{rootMargin:"-30% 0px -60% 0px"});
sections.forEach(s=>observer.observe(s));
const revealObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.08});$$(".reveal").forEach(x=>revealObs.observe(x));

$$(".flow-step").forEach(x=>x.onmouseenter=()=>{const tip=$("#flowTip");tip.textContent=x.dataset.tip;tip.style.display="block";tip.style.left=x.offsetLeft+10+"px";tip.style.top=x.offsetTop-35+"px"});$$(".flow-step").forEach(x=>x.onmouseleave=()=>$("#flowTip").style.display="none");

const stepText={divide:"DIVIDE: The original problem is split into smaller, manageable subproblems.",conquer:"CONQUER: Each subproblem is solved separately, usually using recursion.",combine:"COMBINE: The partial solutions are joined to form the final answer."};
$$(".idea-card").forEach(c=>c.onclick=()=>{$$(".idea-card").forEach(x=>x.classList.remove("selected"));c.classList.add("selected");$("#stepOutput").textContent=stepText[c.dataset.step]});

let flowTimer;
$("#runFlow").onclick=()=>{clearInterval(flowTimer);const nodes=$$("#workFlow .wf-node"),title=$("#stageTitle"),text=$("#stageText"),bar=$("#flowProgress");nodes.forEach(n=>n.classList.remove("active"));let i=0;const labels=[["Divide","Break the original problem into smaller parts."],["Divide","Create smaller subproblems."],["Conquer","Solve the subproblems separately."],["Conquer","Process each smaller solution."],["Combine","Combine results into the final answer."]];flowTimer=setInterval(()=>{nodes.forEach(n=>n.classList.remove("active"));nodes.forEach(n=>{if(+n.dataset.stage===i)n.classList.add("active")});title.textContent=labels[i][0];text.textContent=labels[i][1];bar.style.width=((i+1)/5*100)+"%";i++;if(i>4){clearInterval(flowTimer);toast("Flow completed ✓")}},700)};

const details={
binary:{title:"Binary Search",def:"Searches for an element by repeatedly dividing a sorted search range into two parts.",how:"Compare the target with the middle element. If it is smaller or larger, discard the other half and repeat.",example:"[10,20,30,40,50,60,70] → search 50 → check middle → narrow range → find 50.",complexity:"O(log n) average and worst for a sorted array.",advantages:"Very efficient for large sorted collections.",applications:"Searching in sorted arrays and indexed data."},
merge:{title:"Merge Sort",def:"Divides an array into smaller parts, sorts them, then merges the sorted parts.",how:"Split until single-element arrays remain, then repeatedly merge two sorted runs.",example:"[38,27,43,3] → [38,27] [43,3] → [27,38] [3,43] → [3,27,38,43].",complexity:"O(n log n) average and worst.",advantages:"Predictable performance and stable sorting.",applications:"Large datasets, external sorting and data processing."},
quick:{title:"Quick Sort",def:"Selects a pivot and partitions the array into smaller and larger elements around it.",how:"Choose a pivot, partition values, then recursively sort the partitions.",example:"[8,3,5,1,7], pivot 5 → [3,1] 5 [8,7].",complexity:"O(n log n) average; O(n²) worst.",advantages:"Fast in practice and usually in-place.",applications:"General-purpose sorting and in-memory data."},
strassen:{title:"Strassen's Matrix Multiplication",def:"Divides matrices into smaller blocks and reduces the number of multiplication operations.",how:"Partition matrices into blocks, compute intermediate products, then combine them into the result.",example:"Matrix → smaller blocks → intermediate calculations → final matrix.",complexity:"Approximately O(n^2.81) for square matrices.",advantages:"Can reduce multiplication work for sufficiently large matrices.",applications:"Scientific computing, numerical methods and large matrix calculations."}
};
function showAlgo(key){const d=details[key];const box=$("#algoDetail");box.innerHTML=`<div class="section-head"><div><span class="eyebrow">SELECTED ALGORITHM</span><h3 style="font-size:25px;margin:7px 0">${d.title}</h3></div><button class="btn ghost" id="detailRun">🎮 Open in Lab</button></div><div class="detail-grid"><div class="detail-box"><h4>Definition</h4><p>${d.def}</p></div><div class="detail-box"><h4>How It Works</h4><p>${d.how}</p></div><div class="detail-box"><h4>Example</h4><p>${d.example}</p></div><div class="detail-box"><h4>Time Complexity</h4><p>${d.complexity}</p></div><div class="detail-box"><h4>Advantages</h4><p>${d.advantages}</p></div><div class="detail-box"><h4>Applications</h4><p>${d.applications}</p></div></div>`;box.classList.add("show");$("#detailRun").onclick=()=>{const map={binary:"binary",merge:"merge",quick:"quick",strassen:"merge"};$("#labAlgo").value=map[key];$("#labAlgo").dispatchEvent(new Event("change"));scrollToEl("#visualizer")}}
$$(".algo-card").forEach(c=>c.onclick=()=>{showAlgo(c.dataset.algo);$$(".algo-card").forEach(x=>x.classList.remove("active"));c.classList.add("active")});

const pseudocode={
merge:`MergeSort(A):\n  If A has one element\n    Return A\n  Divide A into two parts\n  Sort both parts\n  Merge the sorted parts\n  Return the sorted array`,
binary:`BinarySearch(A, target):\n  low = 0, high = length(A)-1\n  While low <= high\n    mid = floor((low + high) / 2)\n    If A[mid] == target: Return mid\n    If A[mid] < target: low = mid + 1\n    Else: high = mid - 1\n  Return -1`,
quick:`QuickSort(A):\n  If A has 0 or 1 element\n    Return A\n  Choose a pivot\n  Partition into smaller and larger parts\n  QuickSort(smaller)\n  QuickSort(larger)\n  Combine smaller + pivot + larger`,
strassen:`Strassen(A, B):\n  Divide A and B into four blocks\n  Calculate the seven intermediate products\n  Combine the blocks using additions/subtractions\n  Return the resulting matrix`
};
function updateCode(){ $("#codeBlock").textContent=pseudocode[$("#codeAlgo").value] }
$("#codeAlgo").onchange=updateCode;updateCode();
$("#copyCode").onclick=()=>navigator.clipboard?.writeText($("#codeBlock").textContent).then(()=>toast("Pseudocode copied ✓")).catch(()=>toast("Copy not available"));

const adv=["Easy to break a large problem into smaller parts.","Makes complex problems easier to understand.","Often improves algorithm efficiency.","Works well with recursion.","Useful for large datasets.","Some tasks can be processed in parallel."];
const lim=["Recursion can require extra memory.","Combining results can take additional time.","It is not suitable for every problem.","Some Divide and Conquer algorithms are difficult to design.","Too many recursive calls can increase memory usage."];
$("#advGrid").innerHTML=adv.map(x=>`<div class="feature"><b>✓ ${x}</b><p>Useful when the problem structure naturally supports decomposition.</p></div>`).join("");
$("#limGrid").innerHTML=lim.map(x=>`<div class="feature"><b>⚠ ${x}</b><p>Consider the input size and implementation details before choosing the approach.</p></div>`).join("");
const apps=[["🔎","Searching","Binary Search repeatedly halves a sorted search range."],["↕","Sorting","Merge Sort and Quick Sort divide sorting work into smaller tasks."],["🧮","Matrix Multiplication","Strassen's method divides matrices into blocks."],["🎨","Computer Graphics","Large computational tasks can be decomposed into smaller operations."],["📊","Data Processing","Large datasets can be processed in manageable parts."],["💻","Large-Scale Computation","Independent subproblems may be solved separately or in parallel."]];
$("#appGrid").innerHTML=apps.map((a,i)=>`<button class="application" data-app="${i}"><span class="app-icon">${a[0]}</span>${a[1]}</button>`).join("");
$$(".application").forEach(b=>b.onclick=()=>{const a=apps[b.dataset.app];$$(".application").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#appDescription").textContent=a[2]});

let values=[],paused=false,runToken=0,operations=0;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function parseArray(){return $("#arrayInput").value.split(",").map(Number).filter(Number.isFinite).slice(0,30)}
function renderArray(arr,cls=[],label=""){const stage=$("#visualStage");stage.innerHTML=`${label?`<div class="level-label">${label}</div>`:""}<div class="array-row">${arr.map((v,i)=>`<div class="array-item ${cls.includes(i)?"compare":""}">${v}</div>`).join("")}</div>`}
function setStatus(s){$("#labStatus").textContent=s;$("#operationCount").textContent="Operations: "+operations}
async function waitStep(){while(paused)await sleep(100);if(runToken===0)return false;await sleep(Math.max(100,1250-Number($("#speedRange").value)));return runToken!==0}
async function mergeAnimate(arr,token){const sorted=await mergeRec(arr,0,token);if(token===runToken){renderArray(sorted,sorted.map((_,i)=>i));setStatus("🎉 SORTED SUCCESSFULLY");}}
async function mergeRec(a,depth,token){if(token!==runToken)return a;if(a.length<=1){renderArray(a,a.map((_,i)=>i),`CONQUER · SINGLE ELEMENT`);await waitStep();return a}const mid=Math.floor(a.length/2),left=a.slice(0,mid),right=a.slice(mid);renderArray(a,[],`DIVIDE · SPLIT INTO ${left.length} + ${right.length}`);if(!(await waitStep()))return a;const l=await mergeRec(left,depth+1,token),r=await mergeRec(right,depth+1,token);let out=[],i=0,j=0;while(i<l.length&&j<r.length){operations++;renderArray(l.concat(r),[i,j+l.length],`COMBINE · COMPARE`);setStatus("Comparing "+l[i]+" and "+r[j]);if(!(await waitStep()))return out.concat(l.slice(i),r.slice(j));if(l[i]<=r[j])out.push(l[i++]);else out.push(r[j++])}out=out.concat(l.slice(i),r.slice(j));renderArray(out,out.map((_,k)=>k),`COMBINE · MERGED`);await waitStep();return out}
async function quickAnimate(a,token){if(a.length<=1)return a;const pivot=a[a.length-1],small=[],large=[];for(let i=0;i<a.length-1;i++){operations++;renderArray(a,[i,a.length-1],`QUICK SORT · PIVOT ${pivot}`);setStatus(`Comparing ${a[i]} with pivot ${pivot}`);if(!(await waitStep()))return a;(a[i]<=pivot?small:large).push(a[i])}renderArray(small.concat([pivot],large),[],`PARTITION · SMALLER | PIVOT | LARGER`);await waitStep();return [...await quickAnimate(small,token),pivot,...await quickAnimate(large,token)]}
async function binaryAnimate(a,target,token){a=[...a].sort((x,y)=>x-y);let low=0,high=a.length-1;while(low<=high&&token===runToken){const mid=Math.floor((low+high)/2);operations++;const cls=a.map((_,i)=>i<low||i>high?i:[]).flat();renderArray(a,[],`SEARCH RANGE · LOW ${low} · MID ${mid} · HIGH ${high}`);$("#visualStage").querySelectorAll(".array-item").forEach((el,i)=>{if(i<low||i>high)el.classList.add("eliminated");if(i===mid)el.classList.add("compare")});setStatus(`Checking middle value ${a[mid]}`);if(!(await waitStep()))return;if(a[mid]===target){renderArray(a,[mid],"✓ TARGET FOUND");setStatus(`Found ${target} at index ${mid}`);return}if(a[mid]<target)low=mid+1;else high=mid-1}if(token===runToken){renderArray(a,[],"SEARCH COMPLETE");setStatus("Target not found")}}
async function startLab(){runToken++;const token=runToken;paused=false;operations=0;const type=$("#labAlgo").value;let a=parseArray();if(!a.length){toast("Enter valid numbers");return}$("#targetWrap").classList.toggle("hidden",type!=="binary");setStatus("Running...");if(type==="merge"){renderArray(a,[],"ORIGINAL ARRAY");await waitStep();await mergeAnimate(a,token)}else if(type==="quick"){const result=await quickAnimate(a,token);if(token===runToken){renderArray(result,result.map((_,i)=>i),"SORTED ARRAY");setStatus("🎉 SORTED SUCCESSFULLY")}}else if(type==="binary")await binaryAnimate(a,Number($("#targetInput").value),token)}
$("#startBtn").onclick=startLab;$("#pauseBtn").onclick=()=>{paused=!paused;$("#pauseBtn").textContent=paused?"▶ RESUME":"⏸ PAUSE";setStatus(paused?"Paused":"Running...")};$("#resetBtn").onclick=()=>{runToken=0;paused=false;operations=0;$("#pauseBtn").textContent="⏸ PAUSE";renderArray(parseArray(),[],"READY");setStatus("Ready — enter values and start.")};$("#labAlgo").onchange=()=>{$("#targetWrap").classList.toggle("hidden",$("#labAlgo").value!=="binary");$("#resetBtn").click()};renderArray(parseArray(),[],"READY");

const searchable=[["Home","#home"],["Introduction","#introduction"],["Basic Idea","#basic"],["How It Works","#how"],["Binary Search","#algorithms"],["Merge Sort","#algorithms"],["Quick Sort","#algorithms"],["Strassen Matrix","#algorithms"],["Algorithm Visualizer","#visualizer"],["Pseudocode","#pseudocode"],["Time Complexity","#complexity"],["Advantages","#advantages"],["Limitations","#limitations"],["Applications","#applications"],["Conclusion","#conclusion"],["References","#references"]];
$("#searchInput").oninput=e=>{const q=e.target.value.toLowerCase().trim(),box=$("#searchResults");if(!q){box.style.display="none";return}const hits=searchable.filter(x=>x[0].toLowerCase().includes(q)).slice(0,7);box.innerHTML=hits.map(x=>`<button data-target="${x[1]}">${x[0]}</button>`).join("")||`<button>No result found</button>`;box.style.display="block";box.querySelectorAll("[data-target]").forEach(b=>b.onclick=()=>{scrollToEl(b.dataset.target);box.style.display="none";$("#searchInput").value=""})};
document.addEventListener("click",e=>{if(!e.target.closest(".search-wrap"))$("#searchResults").style.display="none"});
showAlgo("merge");
